### ISSUE TITLE
Monster Tracking

### ISSUE THREAD

**Issue by MarcTowler** [MarcTowler/Discord-RPG-Bot#14]
Put together a system to track win/loss for monsters and how many times a specific player has killed a specfic monster, also bring in a discovery style system for increased chance of criticals, less damage etc

- [x] Win/Loss tracking
- [x] Player vs specific monster tracking
- [ ] Learn about monsters based on number of encounters (think pokedex)

**Comment by MarcTowler** [comment]
database wise, first two are now done, just need to add code to GAPI

**Comment by MarcTowler** [comment]
Added first two checkpoints on GAPI as needed

**Comment by MarcTowler** [comment]
Scrapping the last item for beta 2

**Comment by MarcTowler** [comment]
just realised it has not been implimented or tested, reopening
